name: places
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  flutter_svg: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - res/

  fonts:
    - family: Roboto
      fonts:
        - asset: res/font/Roboto-Regular.ttf
        - asset: res/font/Roboto-Italic.ttf
          style: italic
        - asset: res/font/Roboto-Bold.ttf
        - asset: res/font/Roboto-BoldItalic.ttf
          style: italic
        - asset: res/font/Roboto-Medium.ttf
        - asset: res/font/Roboto-MediumItalic.ttf
          style: italic
        - asset: res/font/Roboto-Black.ttf
        - asset: res/font/Roboto-BlackItalic.ttf
          style: italic
        - asset: res/font/Roboto-Light.ttf
        - asset: res/font/Roboto-LightItalic.ttf
          style: italic
        - asset: res/font/Roboto-Thin.ttf
        - asset: res/font/Roboto-ThinItalic.ttf
          style: italic


